#Instead of using TAB for indentation, use two spaces at the place of one TAB

#Controller to control robot arm joints
robot_arm_controller:
 type: "position_controllers/JointTrajectoryController"
 joints: [joint_base_link1, joint_link12, joint_link23, joint_link34, joint_link4_ee]

#Controller to control end effector joints
hand_ee_controller:
 type: "position_controllers/JointTrajectoryController"
 joints: [joint_ee_outer_right]

#Controller to continuously publish joint states/positions 
joint_state_controller:
 type: "joint_state_controller/JointStateController"
 publish_rate: 50