controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_base_link1
      - joint_link12
      - joint_link23
      - joint_link34
      - joint_link4_ee
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_ee_outer_right
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: home
  - group: hand
    pose: open