#This is a movit contoller connecting follow_joint_trajectory controller with JointTrajectoryController

controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [joint_base_link1, joint_link12, joint_link23, joint_link34, joint_link4_ee]
    
  - name: hand_ee_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [joint_ee_outer_right]
    